adding the user perosnas file
HYF-Class20/Sound-Blog-Platform pull request #7
Opened 2023-11-07 19:49 UTC by Mervatabuamro

## Description

A clear and concise description of what the Pull Request is about.

## General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

2023-11-07 23:02 UTC, Ibrahim86Ali requested changes
its show me an  empty file @Mervatabuamro

2023-11-08 10:07 UTC, Mervatabuamro commented
Now its good

2023-11-09 19:19 UTC, jialvaradob approved these changes

2023-11-10 08:56 UTC, Ibrahim86Ali approved these changes

2023-11-11 16:15 UTC, merged